title: "Juhl.AI Journal"
description: "Notes, reflections, and progress from my AI learning journey."
theme: minima
show_excerpts: true

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/ajuhl" }

header_pages:
  - index.md

timezone: "Etc/UTC"
